version: '3.7'

services:
  web:
    container_name: web
    env_file: ./backend/web/.env
    build: ./backend/web/.
    volumes:
      - ./backend/web:/code/
      - static_volume:/code/staticfiles
    stdin_open: true
    tty: true
    command: gunicorn --bind :8000 bobi_backend.wsgi:application
    networks:
      - backend_network
    environment:
      - CHOKIDAR_USERPOLLING=true
      - DJANGO_SETTINGS_MODULE=bobi_backend.local_settings
    depends_on:
      - db
  backend-server:
    container_name: nginx-back
    build:
      context: ./backend/nginx/.
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - backend_network
  db:
    container_name: db
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    env_file: ./mysql/.env
    environment:
      TZ: 'Asia/Seoul'
    volumes:
      - ./mysql/volume:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
    - backend_network
    # restart: always 
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001

networks:
  backend_network:
    driver: bridge
volumes:
  static_volume: